_merge = "deep"

baseURL = "https://www.ecoindex.fr/"

enableRobotsTXT = true

title = "EcoIndex.fr"

image = "images/logo-ecoindex.jpg"

defaultContentLanguage = "fr"

disableKinds = ["section", "taxonomy", "term"]

# Do not output RSS for home (default output for home is HTML + RSS)
[outputs]
	home = ["HTML"]
