[fr]
	languageCode = "fr"
	contentDir = "content/fr"
	languageName = "Fran√ßais"
	weight = 1
	[fr.params]
		description = "Evaluez gratuitement la performance et l'empreinte environnementale de votre site web"

[en]
	languageCode = "en"
	contentDir = "content/en"
	languageName = "English"
	weight = 2
	[en.params]
		description = "Evaluate the performance and environmental footprint of your website for free"
